# Generated by Django 3.0.5 on 2024-04-24 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=55, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='upload')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=55, unique=True)),
                ('phone', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('location', models.CharField(default='Noida', max_length=50)),
                ('exprience', models.CharField(max_length=45)),
                ('rating1', models.CharField(blank=True, max_length=45, null=True)),
                ('rating2', models.CharField(blank=True, max_length=45, null=True)),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='upload')),
                ('category_w', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mainapp.Category')),
            ],
        ),
    ]
