# Generated by Django 3.0.5 on 2024-04-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0003_auto_20240425_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicebook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
