# Generated by Django 3.0.5 on 2024-04-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0004_servicebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebook',
            name='is_cancell',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebook',
            name='service',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='servicebook',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
