# Generated by Django 3.0.5 on 2024-04-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0005_auto_20240428_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebook',
            name='workerusername',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
