# Generated by Django 3.0.5 on 2024-05-01 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0006_servicebook_workerusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='buyeruser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.Buyer'),
        ),
    ]
