# Generated by Django 3.0.5 on 2024-05-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0008_servicebook_buyerphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='buyeruser',
        ),
        migrations.AddField(
            model_name='worker',
            name='buyeruser',
            field=models.ManyToManyField(blank=True, null=True, to='Mainapp.Buyer'),
        ),
    ]
