# Generated by Django 3.0.5 on 2024-05-08 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0012_auto_20240508_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebook',
            name='cancell',
        ),
    ]
