# Generated by Django 3.0.5 on 2024-05-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0018_auto_20240513_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebook',
            name='service',
        ),
        migrations.AddField(
            model_name='servicebook',
            name='service',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
