# Generated by Django 3.0.5 on 2024-05-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0019_auto_20240513_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
