# Generated by Django 3.0.5 on 2024-05-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0020_auto_20240518_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='username',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
