# Generated by Django 3.0.5 on 2024-05-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0021_auto_20240518_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
