# Generated by Django 3.0.5 on 2024-05-18 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0023_auto_20240518_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebook',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.Feedback'),
        ),
    ]
