# Generated by Django 3.0.5 on 2024-05-18 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0024_servicebook_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebook',
            name='feedback',
        ),
        migrations.AddField(
            model_name='feedback',
            name='servic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.Servicebook'),
        ),
    ]
